### ISSUE TITLE
gsoc proposal

### ISSUE THREAD

**Issue by efg001** [manonthegithub/GSoC-2020#1]
@manonthegithub 
Hi Kirill,
Nice work on your gsoc proposal! I am also very interested in contributing to Camel. In particular with CAMEL-10652. Create a component for Kafka-Stream. 
I see that in your initial contact with Camel you listed out a couple of projects you wanted to work on, and I wanted to check in and see if you still intend to work on CAMEL-10652 this summer? I am looking for projects related to Kafka and am pretty sure that you will be accepted, so if you are have finalized your proposal, I will apply for a different project : )

Sorry to reach out to you in this way. Please feel free to close this issue after you respond.

**Comment by manonthegithub** [comment]
Hey,

I have already discussed and submitted my proposal for Camel, and this issue is a part of it.

Kind regards / Mit freundlichen Grüßen,
Kirill Yankov.

**Comment by efg001** [comment]
Thanks
